# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('created', models.DateField()),
                ('isbn', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
